### ISSUE TITLE
Header is too big

### ISSUE THREAD

**Issue by ghost** [bjorn/tiled-website#1]
The header is just a little too big on my 1366x768 laptop screen. It literally takes up half of the display. Unless a lot more content is going to go into the header, I suggest re-sizing it to be half as tall.

**Comment by bjorn** [comment]
Is this issue still relevant? The header is only meant to be big on the first page.

**Comment by bjorn** [comment]
So the main thing here is: make an alternative thin header for on other pages.

**Comment by ghost** [comment]
I can agree with that. Just so long as that header doesn't end up on documentation pages and such. On the main page it is pretty stylish.
