### ISSUE TITLE
Find a good place to list sponsors

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled-website#4]
There is currently one company donating $100 a month. I'd like to be more explicit about this option and recognize such companies as sponsors and reward them with a banner on the main site, in the hopes of getting more companies interested.

Right now I'm thinking the best place might be right below the big box that explains why Tiled is great (currently having the carousel in it).

There's also the issue with Stepmap, which is not really a sponsor but pays a similar monthly amount for its advertisement. Putting that link at the bottom will probably affect the click-through ratio since currently the link is rather visible.

**Comment by bjorn** [comment]
Sponsors listed now. Stepmap issue still to resolve.

**Comment by ghost** [comment]
What kind of advertising does Stepmap expect from you? The standard banner?

**Comment by bjorn** [comment]
I don't know what they expect, but on http://www.mapeditor.org/ you can see what they are paying for currently. I expect them to want to keep it similar, but if we end up placing them at the bottom then I'll check with them by email whether that's fine.
