### ISSUE TITLE
Downloads page

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled-website#5]
Should show the following in a nice way:
- Tiled Qt 0.9.0 for Windows
- Tiled Qt 0.9.0 for Mac OS X
- Tiled Qt 0.9.0 source
- Ubuntu PPA
- Fedora, openSUSE and CentOS packages
- Daily builds for Windows

Also, it should probably include a message like "Does Tiled help your project and would you like it to become even better? Consider sponsoring Tiled development!", with a link to the "Support Tiled" page.

**Comment by ghost** [comment]
I think some large, shiny, 64x64 or larger download icons, one for each distribution, laid out in a grid would be nice.

**Comment by bjorn** [comment]
I redesigned it a bit after adding all the content, because my original large buttons were too much for all the links on that page I think. I also picked original OS icons rather than the custom ones I had before.

I consider this page done now.
