### ISSUE TITLE
Integrate FancyBox for showing full version of thumbnails

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled-website#8]
Title says it all.

**Comment by ghost** [comment]
FancyBox integration is partially complete. It has been installed but must be configured to your taste.

**Comment by bjorn** [comment]
Yes, things I've been not very happy with:
- The left/right transition is too fancy (read: slow) and would be better to leave out.
- There is no close button.
- When you press a thumbnail, there is no immediate feedback. It seems to wait for the image to be loaded. With the FancyBox currently used on http://www.mapeditor.org/, you immediately get your screen darkened + a loading indicator when clicking a thumbnail.

**Comment by bjorn** [comment]
Image references were fixed in 7957abde4210de68869653345408d82ea91f0f74 (that resolved the lack of close button as well as most of the immediate feedback). The left/right transition was tweaked in 1b184b11651f54078b69a932d4c093fdd51d118a and 416813d3db70475d8748bb99dea598cd4b932e10.
