### ISSUE TITLE
The pop-up bubble on the Google+ button looks messed up

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled-website#9]
Figure out why, fix if possible.

**Comment by ghost** [comment]
You can't really adjust the size of it. It gets loaded into an iFrame. The best you can do is position stuff around it so that it looks symmetrical.

**Comment by bjorn** [comment]
I'm not talking about the size, the size is fine. The problem is that it looks messed up, like this:

![Tiled Map Editor - Mozilla Firefox_2013-02-13_10-23-32](https://f.cloud.github.com/assets/531764/152317/430d1e64-75bf-11e2-9605-1520184a5e8a.png)

On other websites, the box has a nice shadow and not a double arrow. I don't have a clue why this thing would break on our website. The problem shows up on both Firefox and Chrome. It's supposed to look like this:

![Tiled Map Editor - Mozilla Firefox_2013-02-13_10-26-42](https://f.cloud.github.com/assets/531764/152323/89a9087e-75bf-11e2-93a6-ef5526177d9d.png)

**Comment by ghost** [comment]
Now I see what you're saying. I played around with different ways of adding the button but they always produced the same result. The actual button sits inside of an IFRAME element so the stylesheets in the page are not applying to the button itself. I've tried google a few times but I can't find anybody reporting a similar issue. We might need to submit a bug report to google after going live which is less than ideal :(

**Comment by bjorn** [comment]
Issue no longer valid since I decided to remove this pop-up bubble and don't plan to add it back. Social links will be back eventually, but I want them to be rather less intrusive.
